# Generated by Django 2.2.2 on 2019-06-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='winery',
            name='red',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='winery',
            name='white',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
