# Generated by Django 2.2.2 on 2019-06-17 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stop',
            old_name='Tour',
            new_name='tour',
        ),
        migrations.CreateModel(
            name='Winery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('cave', models.BooleanField()),
                ('tours', models.BooleanField()),
                ('notes', models.CharField(max_length=200)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Stop')),
            ],
        ),
    ]
