# Generated by Django 2.2.2 on 2019-06-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190617_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winery',
            name='stop',
        ),
        migrations.AlterField(
            model_name='winery',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='winery',
            name='cave',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='winery',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='winery',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='winery',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='winery',
            name='tours',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='winery',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
