# Generated by Django 2.2.2 on 2019-06-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190617_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='name',
            field=models.CharField(default='New Tour', max_length=40),
        ),
        migrations.AlterField(
            model_name='stop',
            name='hoursopen',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stop',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='stop',
            name='region',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tour',
            name='numberofstops',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='traveldistance',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='traveltime',
            field=models.FloatField(blank=True),
        ),
    ]
