# Generated by Django 2.2.2 on 2019-06-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190617_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(default='Newly Created Tour', max_length=40),
        ),
    ]
