# Generated by Django 2.2 on 2019-06-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190617_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winery',
            old_name='city',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='winery',
            name='cave',
        ),
        migrations.RemoveField(
            model_name='winery',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='winery',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='winery',
            name='tours',
        ),
        migrations.RemoveField(
            model_name='winery',
            name='website',
        ),
        migrations.AddField(
            model_name='winery',
            name='desc',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='winery',
            name='rating',
            field=models.IntegerField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
